import { z } from "zod";
export const providerSchema = z.object({
  title: z.string().max(150),
  address: z.string().max(255),
  website: z.string().max(150),
  email: z.string().max(100).optional().nullable(),
  phone: z.string().max(12).optional(),
  link: z.string().optional().nullable(),
  facebook: z.string().max(150).optional().nullable(),
  instagram: z.string().optional().nullable(),
  brief: z.string().max(150, 'Brief message was too long').optional().nullable(),
  description: z.string().max(2500).optional().nullable(),
  contactName: z.string().optional().nullable(),
  lat: z.string().optional().nullable(),
  lng: z.string().optional().nullable(),
  tags: z.array(z.string()).optional().nullable(),
  quadrant: z.array(z.string()).optional().nullable(),
  ages: z.array(z.string()).optional().nullable(),
  price: z.string().optional().nullable(),
  pickUp: z.string().max(100).optional().nullable(),
  dropOff: z.string().max(100).optional().nullable(),
  dateStart: z.string().optional().nullable(),
  dateEnd: z.string().optional().nullable(),
  userId: z.number().optional().nullable(),
  status: z.enum(["OPEN", "FULL", "UNKNOWN"]).optional().nullable(),
  authorName: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
});

export type ProviderSchema = z.infer<typeof providerSchema>;
