import { z } from "zod";
export const providerSchema = z.object({
  title: z.string().max(150),
  address: z.string().max(255),
  website: z.string().max(150),
  email: z.string().max(100).optional().nullable(),
  phone: z.string().max(12).optional().nullable(),
  link: z.string().optional().nullable(),
  facebook: z.string().max(150).optional().nullable(),
  instagram: z.string().optional().nullable(),
  brief: z.string().max(150, 'Brief message was too long').optional().nullable(),
  description: z.string().max(2500).optional().nullable(),
  contactName: z.string().optional().nullable(),
  lat: z.number(),
  lng: z.number(),
  tags: z.array(z.string()),
  quadrant: z.array(z.string()),
  ages: z.array(z.string()).optional(),
  price: z.string().optional().nullable(),
  pickUp: z.string().max(100).optional().nullable(),
  dropOff: z.string().max(100).optional().nullable(),
  dateStart: z.string().optional(),
  dateEnd: z.string().optional(),
  userId: z.number().optional(),
  status: z.enum(["OPEN", "FULL", "UNKNOWN"]),
  authorName: z.string().optional(),
  id: z.string().optional(),
});
